### PR TITLE
Improve rpath handling and add some flake8

### PR DESCRIPTION
**Pull request by seanfarley**
With these changes, both mac and linux variants will compile.

### CODE REVIEW

**Comment by uniphil** [comment]
Fantastic! Hey @dbaxa any chance you can review/test? No worries at all if not, I just don't have any currently-active projects to test this on myself at the moment. Looks like solid improvements though, so I'll make sure this gets in :smile:

**Comment by dbaxa** [comment]
@uniphil sure.

**Comment by seanfarley** [comment]
After this, I have another PR to update to pygit 0.24.1 😃

**Comment by uniphil** [comment]
:tada:

**Comment by seanfarley** [comment]
Yayyyyyyyyy

**Pull request merged**
