### PR TITLE
v0.22

### PR DESCRIPTION
**Pull request by Graham42**
I think we should make master use the latest version of pygit (v0.22 right now) and then keep a v0.21 branch around as long as pygit maintains it. Thoughts?

### CODE REVIEW

**Comment by uniphil** [comment]
:+1:

I'll try to get this pushed to pypi today

**Comment by uniphil** [comment]
@Graham42, since this is our first `0.22.x` release, shouldn't it be `0.22.0`?

**Comment by Graham42** [comment]
hmm, I really don't know what it should be. We should definitely reflect pygit version, would be nice to also indicate libgit2 version.

To explain what I did, I made up a version number by taking the pygit major (0.22) and then adding together the pygit and libgit2 minors (0 and 2), yielding 0.22.2. 
Example 2: So for pygit 0.21.4 and libgit 0.21.5 I said 0.21.9.

**Comment by uniphil** [comment]
Yeah, we should probably try to make it easy to find out what libgit2 and pygit2 versions are bundled in a venvgit2 release, but I don't think our version number can communicate that well.

`pygit2` just increments the patch digit when they release a new version under a minor release, and it's supposed to work with all `libgit2` releases with the same minor release number, so I think just starting from zero and counting up patch versions as we make releases for `venvgit2` is at least consistent with that and pretty simple.

What do you think of making a changelog section in the readme to document which lib/pygit2 versions are bundled with venvgi2?

eg.:

### v0.22.0 -- 2015-03-26

 * Update to the latest releases
    * libgit2: **v0.22.2**
    * pygit2: **v0.22.0**

**Pull request merged**
